### ISSUE TITLE
Unable to Find Server Plugin

### ISSUE THREAD

**Issue by andreamoro** [ryantam626/jupyterlab_code_formatter#132]
**Describe the bug**
On completing the installation, when the command below is invoked, the following tracelog returns.

```jupyter serverextension enable --py jupyterlab_code_formatter```

**Diagnostic commands**
Please attach the output of the following commands (please format them properly)

- `Known labextensions:
   app dir: /usr/local/share/jupyter/lab
        @8080labs/qgrid v1.1.1  enabled  OK
        @jupyterlab/toc v3.0.0  enabled  OK
        @krassowski/jupyterlab-lsp v1.0.0  enabled  OK
        @ryantam626/jupyterlab_code_formatter v1.2.2  enabled  OK`

- `config dir: /usr/local/etc/jupyter
    jupyter_lsp  enabled
    - Validating...
      jupyter_lsp 0.8.0 OK
    jupyterlab  enabled
    - Validating...
      jupyterlab 2.0.1 OK
    nbresuse  enabled
    - Validating...
      nbresuse  OK`

Mac OS Catalina 10.15.4
Browser Chrome 80.0.3987.149 
python-language-server  0.31.9
jupyter-lsp 0.8.0

**Screenshots**
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-serverextension", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python3.7/site-packages/notebook/serverextensions.py", line 294, in start
    super(ServerExtensionApp, self).start()
  File "/usr/local/lib/python3.7/site-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "/usr/local/lib/python3.7/site-packages/notebook/serverextensions.py", line 211, in start
    self.toggle_server_extension_python(arg)
  File "/usr/local/lib/python3.7/site-packages/notebook/serverextensions.py", line 200, in toggle_server_extension_python
    m, server_exts = _get_server_extension_metadata(package)
  File "/usr/local/lib/python3.7/site-packages/notebook/serverextensions.py", line 328, in _get_server_extension_metadata
    m = import_item(module)
  File "/usr/local/lib/python3.7/site-packages/traitlets/utils/importstring.py", line 42, in import_item
    return __import__(parts[0])
  File "/usr/local/lib/python3.7/site-packages/jupyterlab_code_formatter/__init__.py", line 3, in <module>
    from jupyterlab_code_formatter.handlers import setup_handlers
  File "/usr/local/lib/python3.7/site-packages/jupyterlab_code_formatter/handlers.py", line 8, in <module>
    from jupyterlab_code_formatter.formatters import SERVER_FORMATTERS
  File "/usr/local/lib/python3.7/site-packages/jupyterlab_code_formatter/formatters.py", line 8, in <module>
    import rpy2.robjects
  File "/usr/local/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 18, in <module>
    import rpy2.robjects.functions
  File "/usr/local/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 6, in <module>
    from rpy2.robjects import help
  File "/usr/local/lib/python3.7/site-packages/rpy2/robjects/help.py", line 40, in <module>
    quiet_require('tools')
  File "/usr/local/lib/python3.7/site-packages/rpy2/robjects/help.py", line 35, in quiet_require
    expr = rinterface.parse(expr_txt)
  File "/usr/local/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py", line 40, in _
    cdata = function(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/rpy2/rinterface.py", line 46, in parse
    return _rinterface._parse(robj.__sexp__._cdata, num)
  File "/usr/local/lib/python3.7/site-packages/rpy2/rinterface_lib/_rinterface_capi.py", line 545, in _parse
    openrlib.rlib.R_tryCatchError(
ffi.error: symbol 'R_tryCatchError' not found in library '/Library/Frameworks/R.framework/Resources/lib/libR.dylib': dlsym(0x7fb5e60e6710, R_tryCatchError): symbol not found

**Comment by andreamoro** [comment]
Pip freeze

3to2==1.1.1
appdirs==1.4.3
applib==1.2
appnope==0.1.0
astroid==2.1.0
attrs==18.2.0
autopep8==1.4.3
backcall==0.1.0
backports.csv==1.0.7
backports.functools-lru-cache==1.5
beautifulsoup4==4.8.0
black==19.10b0
bleach==3.1.0
blis==0.2.4
boto==2.49.0
boto3==1.9.227
botocore==1.12.227
cached-property==1.5.1
cachetools==3.0.0
certifi==2018.11.29
cffi==1.14.0
chardet==3.0.4
cheroot==6.5.8
CherryPy==18.2.0
click==7.1.1
cmdln==2.0.0
CodeIntel==2.0.0
cycler==0.10.0
cymem==2.0.2
decorator==4.3.2
defusedxml==0.5.0
docutils==0.15.2
en-core-web-sm==2.1.0
entrypoints==0.3
esprima==4.0.1
feedparser==5.2.1
flake8==3.7.9
flashtext==2.7
future==0.17.1
gensim==3.8.0
google-api-python-client==1.7.7
google-auth==1.6.2
google-auth-httplib2==0.0.3
google-auth-oauthlib==0.2.0
googleads==15.0.1
hext==0.2.3
httplib2==0.12.0
idna==2.8
importlib-metadata==1.6.0
Inflector==2.0.12
ipykernel==5.1.0
ipython==7.2.0
ipython-genutils==0.2.0
ipywidgets==7.4.2
isodate==0.6.0
isort==4.3.8
jaraco.functools==2.0
jedi==0.15.2
Jinja2==2.10
jmespath==0.9.4
joblib==0.13.2
json5==0.8.5
jsonschema==3.0.2
jupyter==1.0.0
jupyter-client==5.3.1
jupyter-console==6.0.0
jupyter-core==4.4.0
jupyter-lsp==0.8.0
jupyterlab==2.0.1
jupyterlab-code-formatter==1.2.2
jupyterlab-server==1.0.6
kiwisolver==1.1.0
kmodes==0.10.1
lab==4.2
lazy-object-proxy==1.3.1
libclang-py3==3.9.0
lxml==4.3.0
MarkupSafe==1.1.0
matplotlib==3.1.1
mccabe==0.6.1
mistune==0.8.4
more-itertools==7.2.0
murmurhash==1.0.2
mysqlclient==1.4.4
nbconvert==5.4.1
nbformat==4.4.0
nbresuse==0.3.3
nltk==3.4.5
notebook==6.0.1
numpy==1.17.0
oauthlib==2.1.0
packaging==20.3
pandas==0.25.1
pandocfilters==1.4.2
parso==0.6.2
pathspec==0.7.0
Pattern==3.6
pbr==5.1.1
pdfminer.six==20181108
pexpect==4.6.0
pickleshare==0.7.5
plac==0.9.6
pluggy==0.13.1
portend==2.5
preshed==2.0.1
prometheus-client==0.5.0
prompt-toolkit==2.0.8
psutil==5.7.0
ptyprocess==0.6.0
py==1.8.1
pyasn1==0.4.5
pyasn1-modules==0.2.3
pycodestyle==2.5.0
pycparser==2.20
pycryptodome==3.9.0
pydocstyle==5.0.2
pyflakes==2.1.1
Pygments==2.3.1
pylint==2.2.2
pyparsing==2.4.2
pyrsistent==0.15.4
pytest==5.4.1
python-dateutil==2.8.0
python-docx==0.8.10
python-jsonrpc-server==0.3.4
python-language-server==0.31.9
pytz==2018.9
PyYAML==3.13
pyzmq==17.1.2
qtconsole==4.4.3
regex==2020.2.20
requests==2.21.0
requests-oauthlib==1.0.0
requests-toolbelt==0.8.0
rope==0.16.0
rpy2==3.2.7
rsa==4.0
s3transfer==0.2.1
scikit-learn==0.21.3
scipy==1.3.1
seaborn==0.9.0
Send2Trash==1.5.0
simplegeneric==0.8.1
simplejson==3.16.0
six==1.11.0
smart-open==1.8.4
snowballstemmer==2.0.0
sortedcontainers==2.1.0
soupsieve==1.9.3
spacy==2.1.8
srsly==0.1.0
stevedore==1.30.0
suds-jurko==0.6
tempora==1.14.1
terminado==0.8.1
testpath==0.4.2
textblob==0.15.3
thinc==7.0.8
toml==0.10.0
tornado==5.1.1
tqdm==4.35.0
traitlets==4.3.2
typed-ast==1.4.1
tzlocal==2.0.0
ujson==1.35
uritemplate==3.0.0
urllib3==1.24.1
virtualenv==16.4.1
virtualenv-clone==0.4.0
virtualenvwrapper==4.8.2
wasabi==0.2.2
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==3.4.2
wrapt==1.11.1
xlrd==1.2.0
xmltodict==0.11.0
yapf==0.29.0
zc.lockfile==2.0
zeep==3.2.0
zipp==3.1.0
zope.cachedescriptors==4.3.1

**Comment by ryantam626** [comment]
Hi! Sorry I was AFK.

It looks like this is a rpy2 error, is there something wrong with your rpy2 installation (or even R itself)?

**Comment by andreamoro** [comment]
I think that I had missed the installation of one module. 
I redid everything from scratch and in the end I got it working.

Though, you should update the main page with the instructions because when it suggests to install the coffee formatters, at some point the example is not surrounded by quote and it fails.
