### ISSUE TITLE
Internal server error in R 

### ISSUE THREAD

**Issue by adityabandla** [ryantam626/jupyterlab_code_formatter#140]
**Checklist prior to opening an issue**
- [x] I have followed fully the installation steps laid out in the documentation site.
- [X] I have restarted jupyterlab.
- [X] I have read the FAQ section in the documentation site.

**Describe the bug**
I can see Apply FormatR formatter (and works) under the Edit menu, but when I click the toolbar icon, I get a pop up message saying Internal Server Error

**Diagnostic commands**
Please attach the output of the following commands (please format them properly)

- `pip freeze`
```
appdirs==1.4.3
appnope==0.1.0
attrs==19.3.0
backcall==0.1.0
black==19.10b0
bleach @ file:///home/conda/feedstock_root/build_artifacts/bleach_1588608214987/work
brotlipy==0.7.0
certifi==2020.4.5.1
cffi==1.14.0
chardet==3.0.4
click==7.1.2
cryptography==2.9.2
decorator==4.4.2
defusedxml==0.6.0
entrypoints==0.3
idna==2.9
importlib-metadata==1.6.0
ipykernel==5.2.1
ipython @ file:///Users/runner/miniforge3/conda-bld/ipython_1588362988322/work
ipython-genutils==0.2.0
isort==4.3.21
jedi==0.17.0
Jinja2==2.11.2
json5==0.9.0
jsonschema==3.2.0
jupyter-client==6.1.3
jupyter-core==4.6.3
jupyterlab==2.1.2
jupyterlab-code-formatter==1.2.5
jupyterlab-server==1.1.1
MarkupSafe==1.1.1
mistune==0.8.4
mypy-extensions==0.4.3
nbconvert==5.6.1
nbformat==5.0.6
notebook==6.0.3
packaging==20.1
pandocfilters==1.4.2
parso==0.7.0
pathspec==0.8.0
pexpect==4.8.0
pickleshare==0.7.5
prometheus-client==0.7.1
prompt-toolkit==3.0.5
ptyprocess==0.6.0
pycparser==2.20
Pygments==2.6.1
pyOpenSSL==19.1.0
pyparsing==2.4.7
pyrsistent==0.16.0
PySocks==1.7.1
python-dateutil==2.8.1
pytz==2020.1
pyzmq==19.0.0
regex==2020.4.4
requests==2.23.0
rpy2==3.1.0
Send2Trash==1.5.0
simplegeneric==0.8.1
six==1.14.0
terminado==0.8.3
testpath==0.4.4
toml==0.10.0
tornado==6.0.4
traitlets==4.3.3
typed-ast==1.4.1
typing-extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1588470653596/work
tzlocal==2.0.0
urllib3==1.25.9
wcwidth==0.1.9
webencodings==0.5.1
zipp==3.1.0
```
- `jupyter labextension list`
```
JupyterLab v2.1.2
Known labextensions:
   app dir: /opt/miniconda3/envs/jupyterlab/share/jupyter/lab
        @ryantam626/jupyterlab_code_formatter v1.2.5  enabled  OK
```
- `jupyter serverextension list`
```
config dir: /Users/aditya/.jupyter
    jupyterlab_code_formatter  enabled 
    - Validating...
      jupyterlab_code_formatter  OK
config dir: /opt/miniconda3/envs/jupyterlab/etc/jupyter
    jupyterlab  enabled 
    - Validating...
      jupyterlab 2.1.2 OK
```

**Comment by ryantam626** [comment]
Anything on the console where you launched jupyter lab?

**Comment by adityabandla** [comment]
```
[E 22:48:44.414 LabApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "291",
      "Authorization": "token 57f46ae121ccc26a7049530e012ac4f413c1af75aea03e87",
      "Plugin-Version": "1.2.5",
      "X-Xsrftoken": "2|67a0b7d2|eb7d301829e22aef6100cc6b2e8f662f|1588840847",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36",
      "Content-Type": "application/json",
      "Accept": "*/*",
      "Origin": "http://localhost:8888",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Dest": "empty",
      "Referer": "http://localhost:8888/lab/workspaces/auto-n",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-GB,en-US;q=0.9,en;q=0.8",
      "Cookie": "_xsrf=2|67a0b7d2|eb7d301829e22aef6100cc6b2e8f662f|1588840847; username-localhost-8888=\"2|1:0|10:1588862921|23:username-localhost-8888|44:M2JhMzE4NDA2ZmRkNDU1Y2EzYmIwY2U1YjhlMWQyNjA=|fea1e6da07c292cf0df99627006a54abd5038d74690164cd420597f1c3c410fb\""
    }
[E 22:48:44.414 LabApp] 500 POST /jupyterlab_code_formatter/format?1588862924403 (::1) 6.11ms referer=http://localhost:8888/lab/workspaces/auto-n
```

**Comment by ryantam626** [comment]
Could you include more of the surrounding lines please? That might give me some more clues of what went wrong

**Comment by adityabandla** [comment]
```
(jupyterlab) aditya@x86_64-apple-darwin13 ~ % jupyter lab
[I 22:48:08.868 LabApp] JupyterLab extension loaded from /opt/miniconda3/envs/jupyterlab/lib/python3.8/site-packages/jupyterlab
[I 22:48:08.868 LabApp] JupyterLab application directory is /opt/miniconda3/envs/jupyterlab/share/jupyter/lab
[I 22:48:09.116 LabApp] Serving notebooks from local directory: /Users/aditya
[I 22:48:09.117 LabApp] The Jupyter Notebook is running at:
[I 22:48:09.117 LabApp] http://localhost:8888/?token=57f46ae121ccc26a7049530e012ac4f413c1af75aea03e87
[I 22:48:09.117 LabApp]  or http://127.0.0.1:8888/?token=57f46ae121ccc26a7049530e012ac4f413c1af75aea03e87
[I 22:48:09.117 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 22:48:09.125 LabApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/aditya/Library/Jupyter/runtime/nbserver-86075-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=57f46ae121ccc26a7049530e012ac4f413c1af75aea03e87
     or http://127.0.0.1:8888/?token=57f46ae121ccc26a7049530e012ac4f413c1af75aea03e87
[I 22:48:10.884 LabApp] 301 GET /lab/workspaces/auto-n/?clone (::1) 3.00ms
[I 22:48:11.876 LabApp] Build is up to date
Generating grammar tables from /opt/miniconda3/envs/jupyterlab/lib/python3.8/site-packages/blib2to3/Grammar.txt
-Writing grammar tables to /Users/aditya/Library/Caches/black/19.10b0/Grammar3.8.2.final.0.pickle
Writing failed: [Errno 2] No such file or directory: '/Users/aditya/Library/Caches/black/19.10b0/tmpqg78oy90'
Generating grammar tables from /opt/miniconda3/envs/jupyterlab/lib/python3.8/site-packages/blib2to3/PatternGrammar.txt
Writing grammar tables to /Users/aditya/Library/Caches/black/19.10b0/PatternGrammar3.8.2.final.0.pickle
Writing failed: [Errno 2] No such file or directory: '/Users/aditya/Library/Caches/black/19.10b0/tmpgu4j_m1r'
[I 22:48:18.523 LabApp] Creating new notebook in /
[I 22:48:18.729 LabApp] Kernel started: fc97bf3e-ffb1-4274-a9f8-1b7a3d6d917d
[I 22:48:19.213 LabApp] Adapting from protocol version 5.0 (kernel fc97bf3e-ffb1-4274-a9f8-1b7a3d6d917d) to 5.3 (client).
[I 22:48:19.214 LabApp] Adapting from protocol version 5.0 (kernel fc97bf3e-ffb1-4274-a9f8-1b7a3d6d917d) to 5.3 (client).
[E 22:48:44.410 LabApp] Uncaught exception POST /jupyterlab_code_formatter/format?1588862924403 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/jupyterlab_code_formatter/format?1588862924403', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/opt/miniconda3/envs/jupyterlab/lib/python3.8/site-packages/tornado/web.py", line 1701, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/opt/miniconda3/envs/jupyterlab/lib/python3.8/site-packages/jupyterlab_code_formatter/handlers.py", line 90, in post
        formatter_instance = SERVER_FORMATTERS.get(data["formatter"])
    KeyError: 'formatter'
[W 22:48:44.414 LabApp] Unhandled error
[E 22:48:44.414 LabApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "291",
      "Authorization": "token 57f46ae121ccc26a7049530e012ac4f413c1af75aea03e87",
      "Plugin-Version": "1.2.5",
      "X-Xsrftoken": "2|67a0b7d2|eb7d301829e22aef6100cc6b2e8f662f|1588840847",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36",
      "Content-Type": "application/json",
      "Accept": "*/*",
      "Origin": "http://localhost:8888",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Dest": "empty",
      "Referer": "http://localhost:8888/lab/workspaces/auto-n",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-GB,en-US;q=0.9,en;q=0.8",
      "Cookie": "_xsrf=2|67a0b7d2|eb7d301829e22aef6100cc6b2e8f662f|1588840847; username-localhost-8888=\"2|1:0|10:1588862921|23:username-localhost-8888|44:M2JhMzE4NDA2ZmRkNDU1Y2EzYmIwY2U1YjhlMWQyNjA=|fea1e6da07c292cf0df99627006a54abd5038d74690164cd420597f1c3c410fb\""
    }
[E 22:48:44.414 LabApp] 500 POST /jupyterlab_code_formatter/format?1588862924403 (::1) 6.11ms referer=http://localhost:8888/lab/workspaces/auto-n
```

**Comment by ryantam626** [comment]
Huh that's pretty weird, but at least it shows why it's raising a HTTP 500. I will investigate soon :+1:

**Comment by ryantam626** [comment]
Hello, I published a new version that should solve the issue.
`pip install -U jupyterlab_code_formatter`
`jupyter labextension update @ryantam626/jupyterlab_code_formatter` should do the trick.

**Comment by ryantam626** [comment]
Closing due to inactivity
