### ISSUE TITLE
ImportError: No module named 'jupyterlab_code_formatter'

### ISSUE THREAD

**Issue by gabegrand** [ryantam626/jupyterlab_code_formatter#163]
**Checklist prior to opening an issue**
- [x] I have followed fully the installation steps laid out in the documentation site.
- [x] I have restarted jupyterlab.
- [x] I have read the FAQ section in the documentation site.

**Describe the bug**
I've installed jupyterlab_code_formatter via conda (`conda install -c conda-forge jupyterlab_code_formatter`). The labextension is installed, but I get the following error when trying to enable the serverextension.

```
>>> jupyter serverextension enable --py jupyterlab_code_formatter --sys-prefix
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-serverextension", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python3.5/dist-packages/notebook/serverextensions.py", line 294, in start
    super(ServerExtensionApp, self).start()
  File "/usr/local/lib/python3.5/dist-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "/usr/local/lib/python3.5/dist-packages/notebook/serverextensions.py", line 211, in start
    self.toggle_server_extension_python(arg)
  File "/usr/local/lib/python3.5/dist-packages/notebook/serverextensions.py", line 200, in toggle_server_extension_python
    m, server_exts = _get_server_extension_metadata(package)
  File "/usr/local/lib/python3.5/dist-packages/notebook/serverextensions.py", line 328, in _get_server_extension_metadata
    m = import_item(module)
  File "/usr/local/lib/python3.5/dist-packages/traitlets/utils/importstring.py", line 42, in import_item
    return __import__(parts[0])
ImportError: No module named 'jupyterlab_code_formatter'
```

The same error occurs regardless of whether I use the `--sys-prefix` flag.

**Diagnostic commands**
Please attach the output of the following commands (please format them properly)

- `pip freeze | grep jupyter`
```
jupyter-client @ file:///home/conda/feedstock_root/build_artifacts/jupyter_client_1594732094290/work
jupyter-core==4.6.3
jupyterlab==2.2.0
jupyterlab-code-formatter @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_code_formatter_1595387642019/work
jupyterlab-server @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_server_1593951277307/work
```

- `conda list jupyter`
```
# Name                    Version                   Build  Channel
jupyter_client            6.1.6                      py_0    conda-forge
jupyter_core              4.6.3            py36h9f0ad1d_1    conda-forge
jupyterlab                2.2.0                      py_0    conda-forge
jupyterlab_code_formatter 1.3.5                      py_0    conda-forge
jupyterlab_server         1.2.0                      py_0    conda-forge
```

- `jupyter labextension list`
```
JupyterLab v2.2.0
Known labextensions:
   app dir: /home/ubuntu/miniconda3/envs/{env_name}/share/jupyter/lab
        @ryantam626/jupyterlab_code_formatter v1.3.5  enabled  OK
```

- `jupyter serverextension list`
```
config dir: /home/ubuntu/miniconda3/envs/{env_name}/etc/jupyter
    ipyparallel.nbextension  enabled
    - Validating...
      ipyparallel.nbextension  OK
    jupyterlab  enabled
    - Validating...
      jupyterlab 2.2.0 OK
config dir: /usr/local/etc/jupyter
    ipyparallel.nbextension  enabled
    - Validating...
      ipyparallel.nbextension  OK
```

**Comment by ryantam626** [comment]
what python version are you using? python3.5?

**Comment by gabegrand** [comment]
I'm on Python 3.6.10. Not sure why Jupyter is installed under python 3.5, so you're right to ask - I'll look into this. Could that be the source of the problem?

**Comment by ryantam626** [comment]
Only 3.6+ is supported so yes

**Comment by ryantam626** [comment]
Hopefully this is solved now! Reopen if not so :+1:
