### ISSUE TITLE
Error on starting Jupyter Lab: "Unable to find server plugin version, consider upgrading."

### ISSUE THREAD

**Issue by manny-goti** [ryantam626/jupyterlab_code_formatter#172]
**Checklist prior to opening an issue**
- [x] I have followed fully the installation steps laid out in the documentation site.
- [x] I have restarted jupyterlab.
- [x] I have read the FAQ section in the documentation site.

**Describe the bug**
I know that issue #111 is basically the same, however, I have repeated all the same steps and I'm still getting the same error and I'm not able to format my code. Another difference I noticed is that when I print out both extension lists, the first line says `Config option 'kernel_spec_manager_class' not recognized by 'ListLabExtensionsApp'`. I'm not sure if this has anything to do with it or not.

**Diagnostic commands**
Please attach the output of the following commands (please format them properly)

- `pip freeze`
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
anaconda-client           1.7.2                      py_0    conda-forge
anaconda-navigator        1.9.12                   py38_0
appdirs                   1.4.4                      py_0
argon2-cffi               20.1.0           py38h1e0a361_1    conda-forge
arrow                     0.17.0           py38h32f6830_0    conda-forge
async_generator           1.10                       py_0    conda-forge
attrs                     20.2.0             pyh9f0ad1d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
backports.tempfile        1.0                        py_0    conda-forge
backports.weakref         1.0.post1       py38h32f6830_1001    conda-forge
beautifulsoup4            4.9.3              pyhb0f4dca_0    conda-forge
binaryornot               0.4.4                      py_1    conda-forge
black                     19.10b0                    py_0
bleach                    3.2.1              pyh9f0ad1d_0    conda-forge
brotlipy                  0.7.0           py38h1e0a361_1000    conda-forge
bzip2                     1.0.8                h516909a_3    conda-forge
ca-certificates           2020.7.22                     0
certifi                   2020.6.20                py38_0
cffi                      1.14.3           py38he30daa8_0
chardet                   3.0.4           py38h32f6830_1007    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
clyent                    1.2.2                      py_1    conda-forge
colorama                  0.4.3                    pypi_0    pypi
conda                     4.8.5                    py38_0
conda-build               3.18.11                  py38_0
conda-env                 2.6.0                         1
conda-package-handling    1.7.0            py38h1e0a361_5    conda-forge
conda-verify              3.4.2                      py_1
cookiecutter              1.7.2              pyh9f0ad1d_0    conda-forge
cryptography              3.1.1            py38h766eaa4_0    conda-forge
dbus                      1.13.16              hb2f20db_0
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
entrypoints               0.3             py38h32f6830_1001    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
filelock                  3.0.12             pyh9f0ad1d_0    conda-forge
fontconfig                2.13.1            he4413a7_1000    conda-forge
freetype                  2.10.2               he06d7ca_0    conda-forge
future                    0.18.2           py38h32f6830_1    conda-forge
gitdb                     4.0.5                    pypi_0    pypi
gitpython                 3.1.9                    pypi_0    pypi
glib                      2.65.0               h3eb4bd4_0
glob2                     0.7                        py_0    conda-forge
gst-plugins-base          1.14.0               hbbd80ab_1
gstreamer                 1.14.0               hb31296c_0
icu                       58.2              hf484d3e_1000    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
importlib-metadata        2.0.0            py38h32f6830_0    conda-forge
importlib_metadata        2.0.0                         0    conda-forge
ipykernel                 5.3.4            py38h23f93f0_0    conda-forge
ipython                   7.18.1           py38h1cdfbd6_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.17.2           py38h32f6830_0    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
jinja2-time               0.2.0                      py_2    conda-forge
jpeg                      9d                   h516909a_0    conda-forge
json5                     0.9.5              pyh9f0ad1d_0    conda-forge
jsonschema                3.2.0            py38h32f6830_1    conda-forge
jupyter_client            6.1.7                      py_0    conda-forge
jupyter_core              4.6.3            py38h32f6830_1    conda-forge
jupyterlab                2.2.8                      py_0    conda-forge
jupyterlab-code-formatter 1.3.6                    pypi_0    pypi
jupyterlab-git            0.22.0                   pypi_0    pypi
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_server         1.2.0                      py_0    conda-forge
lcms2                     2.11                 hbd6801e_0    conda-forge
ld_impl_linux-64          2.35                 h769bd43_9    conda-forge
libarchive                3.3.3             hb44662c_1005    conda-forge
libffi                    3.3                  he6710b0_2
libgcc-ng                 9.3.0               h5dbcf3e_17    conda-forge
libgomp                   9.3.0               h5dbcf3e_17    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblief                   0.10.1               he1b5a44_1    conda-forge
libpng                    1.6.37               hed695b0_2    conda-forge
libsodium                 1.0.18               h516909a_1    conda-forge
libstdcxx-ng              9.3.0               h2ae2ef3_17    conda-forge
libtiff                   4.1.0                hc7e4089_6    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libwebp-base              1.1.0                h516909a_3    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.9                h13577e0_2    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
markupsafe                1.1.1            py38h1e0a361_1    conda-forge
mistune                   0.8.4           py38h1e0a361_1001    conda-forge
mypy_extensions           0.4.3                    py38_0
navigator-updater         0.2.1                    py38_0
nb_conda                  2.2.1                    py38_1
nb_conda_kernels          2.3.0            py38h32f6830_1    conda-forge
nbclient                  0.5.0                      py_0    conda-forge
nbconvert                 6.0.7            py38h32f6830_0    conda-forge
nbdime                    2.1.0                    pypi_0    pypi
nbformat                  5.0.7                      py_0    conda-forge
ncurses                   6.2                  he1b5a44_1    conda-forge
nest-asyncio              1.4.1                      py_0    conda-forge
notebook                  6.1.4            py38h32f6830_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openssl                   1.1.1h               h7b6447c_0
packaging                 20.4               pyh9f0ad1d_0    conda-forge
pandoc                    2.10.1               h516909a_0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.7.1              pyh9f0ad1d_0    conda-forge
patchelf                  0.11                 he1b5a44_0    conda-forge
pathspec                  0.7.0                      py_0
pcre                      8.44                 he1b5a44_0    conda-forge
pexpect                   4.8.0            py38h32f6830_1    conda-forge
pickleshare               0.7.5           py38h32f6830_1001    conda-forge
pillow                    7.2.0            py38h9776b28_1    conda-forge
pip                       20.2.3                     py_0    conda-forge
pkginfo                   1.5.0.1                    py_0    conda-forge
poyo                      0.5.0                      py_0    conda-forge
prometheus_client         0.8.0              pyh9f0ad1d_0    conda-forge
prompt-toolkit            3.0.7                      py_0    conda-forge
psutil                    5.7.2            py38h1e0a361_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
py-lief                   0.10.1           py38h950e882_1    conda-forge
pycosat                   0.6.3           py38h1e0a361_1004    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygments                  2.7.1                      py_0    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.9.2            py38h05f1152_4
pyrsistent                0.17.3           py38h1e0a361_0    conda-forge
pysocks                   1.7.1            py38h32f6830_1    conda-forge
python                    3.8.3                hcff3b4d_2
python-dateutil           2.8.1                      py_0    conda-forge
python-libarchive-c       2.9              py38h32f6830_1    conda-forge
python-slugify            4.0.1              pyh9f0ad1d_0    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
pyyaml                    5.3.1            py38h1e0a361_0    conda-forge
pyzmq                     19.0.2           py38ha71036d_1    conda-forge
qt                        5.9.7                h5867ecd_1
qtpy                      1.9.0                      py_0    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
regex                     2020.7.14        py38h7b6447c_0
requests                  2.24.0             pyh9f0ad1d_0    conda-forge
ripgrep                   12.1.1               h516909a_0    conda-forge
ruamel_yaml               0.15.80         py38h1e0a361_1002    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                49.6.0           py38h32f6830_1    conda-forge
sip                       4.19.13          py38he6710b0_0
six                       1.15.0             pyh9f0ad1d_0    conda-forge
smmap                     3.0.4                    pypi_0    pypi
soupsieve                 2.0.1                      py_1    conda-forge
sqlite                    3.33.0               h4cf870e_1    conda-forge
terminado                 0.9.1            py38h32f6830_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
text-unidecode            1.3                        py_0    conda-forge
tk                        8.6.10               hed695b0_1    conda-forge
toml                      0.10.1                     py_0
tornado                   6.0.4            py38h1e0a361_1    conda-forge
tqdm                      4.50.1             pyh9f0ad1d_0    conda-forge
traitlets                 5.0.4                      py_1    conda-forge
typed-ast                 1.4.1            py38h7b6447c_0
typing_extensions         3.7.4.3                    py_0
unidecode                 1.1.1                      py_0    conda-forge
urllib3                   1.25.10                    py_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
whichcraft                0.6.1                      py_0    conda-forge
xmltodict                 0.12.0                     py_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zeromq                    4.3.3                he1b5a44_2    conda-forge
zipp                      3.3.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1009    conda-forge
zstd                      1.4.4                h3b9ef0a_2    conda-forge
```

- `jupyter labextension list`
```
Config option `kernel_spec_manager_class` not recognized by `ListLabExtensionsApp`.
JupyterLab v2.2.8
Known labextensions:
   app dir: /home/mgoti/anaconda3/share/jupyter/lab
        @jupyterlab/git v0.22.0  enabled  OK
        @ryantam626/jupyterlab_code_formatter v1.3.6  enabled  OK
        nbdime-jupyterlab v2.0.1  enabled  OK
```
- `jupyter serverextension list`
```
Config option `kernel_spec_manager_class` not recognized by `ListLabExtensionsApp`.
JupyterLab v2.2.8
Known labextensions:
   app dir: /home/mgoti/anaconda3/share/jupyter/lab
        @jupyterlab/git v0.22.0  enabled  OK
        @ryantam626/jupyterlab_code_formatter v1.3.6  enabled  OK
        nbdime-jupyterlab v2.0.1  enabled  OK
(base) [mgoti@localhost root]$ jupyter serverextension list
Config option `kernel_spec_manager_class` not recognized by `ListServerExtensionsApp`.
config dir: /home/mgoti/.jupyter
    jupyterlab_code_formatter  enabled
    - Validating...
      jupyterlab_code_formatter  OK
config dir: /home/mgoti/anaconda3/etc/jupyter
    jupyterlab  enabled
    - Validating...
      jupyterlab 2.2.8 OK
    jupyterlab_git  enabled
    - Validating...
      jupyterlab_git 0.22.0 OK
    nbdime  enabled
    - Validating...
      nbdime 2.1.0 OK
```

**Screenshots**
![image](https://user-images.githubusercontent.com/8884630/95496758-4b0b8c80-096f-11eb-99cc-3922f2a4026b.png)

**Additional context**

**Comment by ryantam626** [comment]
Is there anything interesting in the terminal where you start jupyterlab?

If I were you, I would try to fix the jupyter config to rule out that being the issue here, as that's likely to be the cause.

**Comment by manny-goti** [comment]
Yea, I'll try and do a fresh install on a new environment and see what happens.

**Comment by niloatgoshare** [comment]
Im creating new environments programmatically, and Im also getting this error.
When I start the jupyter lab server, it outputs 
```
[I 14:56:57.698 LabApp] JupyterLab extension loaded from /home/nilo/anaconda3/envs/project_name/lib/python3.8/site-packages/jupyterlab
[I 14:56:57.698 LabApp] JupyterLab application directory is /home/nilo/anaconda3/envs/project_name/share/jupyter/lab
[W 14:56:57.700 LabApp] Error loading server extension jupyterlab_code_formatter
    Traceback (most recent call last):
      File "/home/nilo/anaconda3/envs/project_name/lib/python3.8/site-packages/notebook/notebookapp.py", line 1942, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/home/nilo/anaconda3/envs/project_name/lib/python3.8/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'jupyterlab_code_formatter'

```

```
jupyter labextension list
JupyterLab v2.2.8
Known labextensions:
   app dir: /home/nilo/anaconda3/envs/project_name/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        @jupyterlab/toc v4.0.0  enabled  OK
        @ryantam626/jupyterlab_code_formatter v1.3.6  enabled  OK
        jupyterlab-jupytext v1.2.1  enabled  OK
        jupyterlab-plotly v4.9.0  enabled  OK
        plotlywidget v4.9.0  enabled  OK
```

**Comment by ryantam626** [comment]
> Im creating new environments programmatically, and Im also getting this error.
> When I start the jupyter lab server, it outputs
> 
> ```
> [I 14:56:57.698 LabApp] JupyterLab extension loaded from /home/nilo/anaconda3/envs/project_name/lib/python3.8/site-packages/jupyterlab
> [I 14:56:57.698 LabApp] JupyterLab application directory is /home/nilo/anaconda3/envs/project_name/share/jupyter/lab
> [W 14:56:57.700 LabApp] Error loading server extension jupyterlab_code_formatter
>     Traceback (most recent call last):
>       File "/home/nilo/anaconda3/envs/project_name/lib/python3.8/site-packages/notebook/notebookapp.py", line 1942, in init_server_extensions
>         mod = importlib.import_module(modulename)
>       File "/home/nilo/anaconda3/envs/project_name/lib/python3.8/importlib/__init__.py", line 127, in import_module
>         return _bootstrap._gcd_import(name[level:], package, level)
>       File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
>       File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>       File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
>     ModuleNotFoundError: No module named 'jupyterlab_code_formatter'
> ```
> 
> ```
> jupyter labextension list
> JupyterLab v2.2.8
> Known labextensions:
>    app dir: /home/nilo/anaconda3/envs/project_name/share/jupyter/lab
>         @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
>         @jupyterlab/toc v4.0.0  enabled  OK
>         @ryantam626/jupyterlab_code_formatter v1.3.6  enabled  OK
>         jupyterlab-jupytext v1.2.1  enabled  OK
>         jupyterlab-plotly v4.9.0  enabled  OK
>         plotlywidget v4.9.0  enabled  OK
> ```

Don't think you have the server plugin installed, follow [this](https://jupyterlab-code-formatter.readthedocs.io/en/latest/installation.html#installation-step-1-installing-the-plugin-itself)

**Comment by a0th** [comment]
Hey @ryantam626 , thanks for the reply.

Should 
`@ryantam626/jupyterlab_code_formatter v1.3.6  enabled  OK` mean that the plugin is installed?

**Comment by a0th** [comment]
Holy moly, sorry about that, you are right, the `jupyterlab_code_formatter` was not in the `environment.yml`. Thank you very much!
