### ISSUE TITLE
Minimal python now 3.9? functools.cache required

### ISSUE THREAD

**Issue by enryH** [ryantam626/jupyterlab_code_formatter#313]
I wonder which is the latest supported version. The software uses [`functools.cache` ](https://docs.python.org/3/library/functools.html#functools.cache) which was added in python 3.9, a wrapper around `lru_cache`. Is this intendend?

```cmd
# 2.0.0
>>> jupyter lab
[W 2023-05-20 11:33:18.562 ServerApp] jupyterlab_code_formatter | error adding extension (enabled: True): The module 'jupyterlab_code_formatter' could not be found (cannot import name 'cache' 
from 'functools' (C:\Users\user\Anaconda3\envs\env\lib\functools.py)). Are you sure the extension is installed?
    Traceback (most recent call last):
      File "C:\Users\user\Anaconda3\envs\env\lib\site-packages\jupyter_server\extension\manager.py", line 175, in _validate_name
        self._module, self._metadata = get_metadata(name)
      File "C:\Users\user\Anaconda3\envs\env\lib\site-packages\jupyter_server\extension\utils.py", line 55, in get_metadata
        module = importlib.import_module(package_name)
      File "C:\Users\user\Anaconda3\envs\env\lib\importlib\__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 843, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "C:\Users\user\Anaconda3\envs\env\lib\site-packages\jupyterlab_code_formatter\__init__.py", line 2, in <module>
        from .handlers import setup_handlers
      File "C:\Users\user\Anaconda3\envs\env\lib\site-packages\jupyterlab_code_formatter\handlers.py", line 7, in <module>
        from jupyterlab_code_formatter.formatters import SERVER_FORMATTERS
      File "C:\Users\user\Anaconda3\envs\env\lib\site-packages\jupyterlab_code_formatter\formatters.py", line 17, in <module>
        from functools import cache
    ImportError: cannot import name 'cache' from 'functools' (C:\Users\user\Anaconda3\envs\env\lib\functools.py)
```

**Comment by pdhall99** [comment]
Python >=3.7 compatibility will be restored in the next release. See issue https://github.com/ryantam626/jupyterlab_code_formatter/issues/309.

**Comment by ryantam626** [comment]
Hello, I have now released 2.2.1 which should hopefully resolve this, could you confirm please?

**Comment by enryH** [comment]
Yes, this let's me start without an error, however it complains now that 

```
Jupyterlab Code Formatter Error
Unable to find default formatters to use, please file an issue on GitHub.
```

which is probably some installation issue on my side... It also had some problem before so therefore I updated...

````cmd
jupyterlab                     3.5.3            py38haa95532_0
jupyterlab_server         2.12.0           py38haa95532_0
jupyter_server              1.23.4           py38haa95532_0
```

**Comment by ryantam626** [comment]
Ah, would you mind upgrading to jupyterlab 3.6+?
The minimial supported jupyterlab version is 3.6+ going forward.

**Comment by enryH** [comment]
In principle not, but in the current conda environment I am using I have tested now certain dependencies based on the channel priority of first `defaults` and then `conda-forge`. Where can I see which is the last jupyterlab_code_formatter version that supports `3.5.3`, which is the latest available on the `defaults` channel provided by Anaconda.

**Comment by ryantam626** [comment]
In theory that should be `<2.1` as you said, but I messed up something during release so I am not 100% sure it will work.

Since you are using conda, better stick to the `1.x.x` versions, I don't think the `2.x.x` versions have been working on conda-forge at the moment.

Also, just curious, is there a particular why are you using the conda package as opposed to `pip` section in conda?

**Comment by enryH** [comment]
It's rather a habit as I hope that dependencies are then resolved via conda. But as most wheels are provided now using pip, it's less necessary to use conda...

I downgraded to `1.6.1`, but then the error from before re-occurs, namely that jupyterlab_code_server cannot be found:

```
Server Connection Error
A connection to the Jupyter server could not be established. JupyterLab will continue trying to reconnect. Check your network connection or Jupyter server configuration.
```
```
# Name                    Version                   Build  Channel
jupyter-dash              0.4.2            py38haa95532_0
jupyter-resource-usage    0.5.1              pyhd8ed1ab_0    conda-forge
jupyter-server-mathjax    0.2.4              pyhc268e32_0    conda-forge
jupyter_client            8.1.0            py38haa95532_0
jupyter_contrib_core      0.3.3                      py_2    conda-forge
jupyter_contrib_nbextensions 0.5.1              pyhd8ed1ab_2    conda-forge
jupyter_core              5.3.0            py38haa95532_0
jupyter_highlight_selected_word 0.2.0           py38haa244fe_1005    conda-forge
jupyter_latex_envs        1.4.6           pyhd8ed1ab_1002    conda-forge
jupyter_nbextensions_configurator 0.4.1            py38haa244fe_2    conda-forge
jupyter_server            1.23.4           py38haa95532_0
jupyterlab                3.5.3            py38haa95532_0
jupyterlab-git            0.41.0             pyhd8ed1ab_1    conda-forge
jupyterlab-system-monitor 0.8.0              pyhd8ed1ab_1    conda-forge
jupyterlab-topbar         0.6.1              pyhd8ed1ab_2    conda-forge
jupyterlab_code_formatter 1.6.1              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.1.2                      py_0
jupyterlab_server         2.22.0           py38haa95532_0
jupyterlab_widgets        3.0.5            py38haa95532_0
notebook                  6.5.4            py38haa95532_0
notebook-shim             0.2.2            py38haa95532_0
```

**Comment by ryantam626** [comment]
Sorry I am confused, is this still an issue?

**Comment by enryH** [comment]
No, I think you changed the functionality regarding `lru_cache`. The older version support was a secondary issue which does not matter to much if it works with latest versions.
