### ISSUE TITLE
500s "TypeError: expected string or bytes-like object"

### ISSUE THREAD

**Issue by daturkel** [ryantam626/jupyterlab_code_formatter#98]
Hello, I've been using this extension for a while now with no issues, but I recently started getting 500 errors when trying to run format.

Here is an example error:
```
[E 16:05:45.040 LabApp] Uncaught exception POST /jupyterlab_code_formatter/format?1576271145035 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/jupyterlab_code_formatter/format?1576271145035', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/Users/danturkel/.local/share/virtualenvs/mir/lib/python3.7/site-packages/tornado/web.py", line 1697, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/Users/danturkel/.local/share/virtualenvs/mir/lib/python3.7/site-packages/jupyterlab_code_formatter/handlers.py", line 66, in post
        data["code"], **(data["options"] or {})
      File "/Users/danturkel/.local/share/virtualenvs/mir/lib/python3.7/site-packages/jupyterlab_code_formatter/formatters.py", line 37, in format_code
        code = re.sub("^%", "#%#", code, flags=re.M)
      File "/Users/danturkel/anaconda3/lib/python3.7/re.py", line 192, in sub
        return _compile(pattern, flags).sub(repl, string, count)
    TypeError: expected string or bytes-like object
[W 16:05:45.041 LabApp] Unhandled error
[E 16:05:45.042 LabApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "538",
      "Authorization": "token 5513ef11a86f3c116c9f9c1cf2021e0b57cf558d4da5ddee",
      "Origin": "http://localhost:8888",
      "X-Xsrftoken": "2|25de0971|338b95eda34187d4fae397ef072658e3|1576021408",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36",
      "Dnt": "1",
      "Content-Type": "application/json",
      "Accept": "*/*",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Referer": "http://localhost:8888/lab/workspaces/auto-J",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9",
      "Cookie": "username-localhost-8889=\"2|1:0|10:1574374756|23:username-localhost-8889|44:ODVkZjFlMWRiNmRmNDJmNzk3OWFhM2E2NzlmZWFjZjA=|3423f1519a67ce53ec799cad9e9c7a6114c59414377b8d224b12d94d3b412243\"; _xsrf=2|25de0971|338b95eda34187d4fae397ef072658e3|1576021408; username-localhost-8888=\"2|1:0|10:1576271144|23:username-localhost-8888|44:YWVjOTNkNGM4NjY2NGY2Mjk2ODQxODM5ZWM5MTExNGI=|456d2688f332842b03fdde263cf4469de66b3d2a822d983fe93fed465d9e8cca\""
    }
[E 16:05:45.042 LabApp] 500 POST /jupyterlab_code_formatter/format?1576271145035 (::1) 2.15ms referer=http://localhost:8888/lab/workspaces/auto-J
```

Below are my versions:

```
jupyter                           1.0.0
jupyter-client                    5.3.3
jupyter-console                   6.0.0
jupyter-contrib-core              0.3.3
jupyter-core                      4.5.0
jupyter-nbextensions-configurator 0.4.1
jupyterlab                        1.2.4
jupyterlab-black                  0.2.1
jupyterlab-code-formatter         0.5.2
jupyterlab-server                 1.0.6
```
```
Enabling notebook extension jupyter-black-master/jupyter-black...
      - Validating: OK
```
```
JupyterLab v1.2.4
Known labextensions:
   app dir: /Users/danturkel/.local/share/virtualenvs/mir/share/jupyter/lab
        @ryantam626/jupyterlab_code_formatter v1.0.3  enabled  OK
```

**Comment by ryantam626** [comment]
You have an outdated python package.
Try `pip install -U jupyterlab-code-formatter`.

**Comment by daturkel** [comment]
The one thing I didn't update, of course! 

Thanks so much.
